/** Declaration file generated by dts-gen */

export = mongoose_delete;

declare function mongoose_delete(schema: any, options: any, ...args: any[]): any;

declare namespace mongoose_delete {
    const prototype: {};
}